package controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import DAO.UserDAO;
import javafx.event.ActionEvent;

public class SignSceneController {
	@FXML
	private TextField tfUsernameUp;
	@FXML
	private TextField tfLastNameUp;
	@FXML
	private TextField tfNameUp;
	@FXML
	private TextField tfEmailUp;
	@FXML
	private TextField tfPasswordUp;
	@FXML
	private Button btnSignUp;
	@FXML
	private TextField tfUsername;
	@FXML
	private TextField tfPassword;
	@FXML
	private Button btnSignIn;
	
	private Parent root;
	private Scene scene;
	private Stage stage;

	// Event Listener on Button[#btnSignUp].onAction
	@FXML
	public void btnSignUp(ActionEvent event) {
		// TODO Autogenerated
		String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
		Pattern pattern = Pattern.compile(regex);
		Matcher matcher = pattern.matcher(tfEmailUp.getText());
		
		if(tfUsernameUp.getText()=="") {
			Alert alert=new Alert(AlertType.ERROR,"username required !");
			alert.show();
		}else if(UserDAO.getUser(tfUsernameUp.getText())) {
			Alert alert=new Alert(AlertType.ERROR,"username taken !");
			alert.show();
		}else if(tfNameUp.getText()=="") {
			Alert alert=new Alert(AlertType.ERROR,"name required !");
			alert.show();
		}else if(tfLastNameUp.getText()=="") {
			Alert alert=new Alert(AlertType.ERROR,"Lastname required !");
			alert.show();
		}else if(tfEmailUp.getText()=="") {
			Alert alert=new Alert(AlertType.ERROR,"Email required !");
			alert.show();
		}else  if(!matcher.matches()) {
			Alert alert=new Alert(AlertType.ERROR,"Invalid Email !");
			alert.show();
		}else  if(tfPasswordUp.getText()=="") {
			Alert alert=new Alert(AlertType.ERROR,"Password required !");
			alert.show();
		}else {
		UserDAO.inserer(tfUsernameUp.getText(), tfNameUp.getText(), tfLastNameUp.getText(), tfEmailUp.getText(), tfPasswordUp.getText());
		Alert alert=new Alert(AlertType.INFORMATION,"user added !");
		alert.show();
		}
	}
	// Event Listener on Button[#btnSignIn].onAction
	@FXML
	public void btnSignIn(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		if(!UserDAO.authentification(tfUsername.getText(),tfPassword.getText())) {
			Alert alert=new Alert(AlertType.INFORMATION,"user doesn't exist");
			alert.show();
		}else {
			switchScene(event,"Posting.fxml");
		}
	}
	
	public void switchScene(ActionEvent event,String viewName) throws IOException {
		Parent root= FXMLLoader.load(getClass().getResource("/interfaces/"+viewName));
		stage=(Stage)((Node) event.getSource()).getScene().getWindow() ;
		scene=new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}


